### ISSUE TITLE
Case diagram

### ISSUE THREAD

**Issue by KateIbom** [BNU-550/asp-team-project-clutchcoders#2]
We need to add another actor called manager to the case diagram

**Comment by VincentA55** [comment]
Hi kate,
I agree with that. I can do that because i am the Supreme designer, as you know.
I can have that done before next week

**Comment by KateIbom** [comment]
Thanks for that  supreme designer!!!

**Comment by VincentA55** [comment]
Dont thank me yet! I havent actually done anything!

**Comment by KateTurton** [comment]
Hi Matt, can you have a look at the use case diagram plan a rough class diagram in preparation for next week.
